# Generated by Django 2.2 on 2020-01-26 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0002_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={},
        ),
    ]
